.authenticate-to-npmjs:
  - &authenticate-to-npmjs |
    echo "$NPM_SCOPE:registry=https://$NPM_REGISTRY_HOST/" >> ~/.npmrc
    echo "//$NPM_REGISTRY_HOST/:_authToken=$NPM_TOKEN" >> ~/.npmrc

stages:
  - build
  - publish

build:
  stage: build
  image: node:8-alpine
  script:
    - node --version
    - npm --version
    - npm run build

publish:
  stage: publish
  image: node:8-alpine
  script:
    - node --version
    - npm --version
    - *authenticate-to-npmjs
    - npm install
    - npm run make-distribution
    - apk add git # TODO: use an image that already has git
    - cd lib/main
    - npm shrinkwrap
    - export RM_TMP_TAG=$(date +%s)
    - npm publish --access public --tag $RM_TMP_TAG
    - ./tag-nodejs
  only:
    - /^\d+\.\d+\.\d+(\-[^\.]+\.\d+)?$/
