.authenticate-to-npmjs:
  - &authenticate-to-npmjs |
    echo "$NPM_SCOPE:registry=https://$NPM_REGISTRY_HOST/" >> ~/.npmrc
    echo "//$NPM_REGISTRY_HOST/:_authToken=$NPM_TOKEN" >> ~/.npmrc

stages:
  - build
  - publish

build:
  stage: build
  image: node:8-alpine
  script:
    - node --version
    - npm --version
    - npm run build

publish:
  stage: publish
  image: node:8-alpine
  script:
    - node --version
    - npm --version
    - *authenticate-to-npmjs
    - npm install
    - npm run make-distribution
    - apk add git
    - cd lib/main
    - export VERSION=$(node -e 'process.stdout.write(require("./package.json").version)')
    - export MINOR_VERSION=$(echo -n $VERSION | egrep -o '^\d+\.\d+')
    - export GREATEST_MINOR_VERSION="$(git ls-remote origin | grep refs/heads | egrep -o '/v\d+\.\d+$' | egrep -o '\d+\.\d+$' | sort -t . -k 1,1n -k 2,2n | tail +1)"
    - export TAG=stable
    - if [ -n "$(echo -n "$VERSION" | egrep -o '\-(pre|rc)\.\d+$')" ]; then export TAG=next; fi
    - if [ "$TAG" == "stable" ] && [ "$MINOR_VERSION" == "$GREATEST_MINOR_VERSION" ]; then export TAG=""; fi
    - if [ -n "$TAG" ]; then export TAG="--tag $TAG-$MINOR_VERSION"; fi
    - npm shrinkwrap
    - npm publish --access public $TAG
  only:
    - /^([0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}(-(pre|rc)\.[0-9]{1,})?)$/
