.authenticate-to-npmjs:
  - &authenticate-to-npmjs |
    echo "$NPM_SCOPE:registry=https://$NPM_REGISTRY_HOST/" >> ~/.npmrc
    echo "//$NPM_REGISTRY_HOST/:_authToken=$NPM_TOKEN" >> ~/.npmrc

stages:
  - build
  - publish

build:
  stage: build
  image: node:8-alpine
  script:
    - node --version
    - npm --version
    - npm run build

publish:
  stage: publish
  image: node:8-alpine
  script:
    - node --version
    - npm --version
    - *authenticate-to-npmjs
    - npm install
    - npm run make-distribution
    - cd lib/main
    - export VERSION=$(node -e 'process.stdout.write(require("./package.json").version)')
    - export MINOR_VERSION=$(echo -n $VERSION | egrep -o '^\d+\.\d+')
    - export TAG=stable
    - if [ -n "$(echo -n "$VERSION" | egrep -o '(pre|rc)')" ]; then export TAG=next; fi
    - npm shrinkwrap
    - npm publish --access public --tag $TAG-$MINOR_VERSION
  only:
    - /^([0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}(-(pre|rc)\.[0-9]{1,})?)$/
